const Constants = {
  Prefix: '!',
  ServerName: 'UCF CS Discord',
  Channels: {
    Public: {
      Welcome: 'welcome',
      Announcements: 'announcements',
      CodeOfConduct: 'code_of_conduct',
      ClassInvite: 'class_invite',
      Pets: 'pets',
      General: 'general',
      Food: 'food',
      Anime: 'anime',
      Media: 'media',
      Networking: 'networking',
      VideoGames: 'video_games',
      EventBoard: 'event_board',
      BuySellTrade: 'buy_sell_trade',
      HelpfulBaubles: 'helpful_baubles',
      ServerRequests: 'server_requests',
      PersonalProjects: 'personal_projects',
      Security: 'security',
      Industry: 'industry',
      Academia: 'academia',
      Hardware: 'hardware',
      FlameWars: 'flame_wars',
      OsSoftware: 'os_software',
      DataScience: 'data_science',
      FoundationExam: 'foundation_exam',
      WebDevelopment: 'web_development',
      MathScienceHelp: 'math_science_help',
      ProgrammingHelp: 'programming_help',
      GameDevelopment: 'game_development',
      InternetNetworking: 'internet_networking',
      AudioSlate: 'audio_slate',
    },
    Staff: {
      ModChat: 'mod_chat',
      UserOffenses: 'user_offenses',
    },
    Admin: {
      AdminChannel: 'admin_chat',
      BotLogs: 'bot_logs',
    },
    Private: {},
    Bot: {
      BotChannel: 'bot_commands',
    },
  },
};

export default Constants;
