const Constants = {
  MaxCharCount: 2000,
  Prefix: '!',
  ServerName: 'UCF CS, ECE, and IT',
  LionPFP:
    'https://cdn.discordapp.com/avatars/574623716638720000/7d404c72a6fccb4a3bc610490f8d7b72.png',
  Channels: {
    Public: {
      Announcements: 'announcements',
      Welcome: 'welcome',
      ClassInvite: 'class_invite',
      AlumniLounge: 'alumni_lounge',
      ServerRequests: 'server_requests',
      CodeOfConduct: 'code_of_conduct',
      ClubOfficers: 'clubOfficers',
      Pets: 'pets',
      Clubs: 'clubs',
      Travel: 'travel',
      Memes: 'memes',
      General: 'general',
      Networking: 'networking',
      BulletinBoard: 'bulletin_board',
      PersonalProjects: 'personal_projects',
      HorticultureChat: 'horticulture_chat',
      ClubAnnouncements: 'club_announcements',
      Food: 'food',
      Media: 'media',
      Sports: 'sports',
      Fitness: 'fitness',
      Finance: 'finance',
      Vehicles: 'vehicles',
      Politics: 'politics',
      VideoGames: 'video_games',
      Advising: 'advising',
      ProjectIdeas: 'project_ideas',
      FoundationExam: 'foundation_exam',
      ProgrammingHelp: 'programming_help',
      MathScienceHelp: 'math_science_help',
      Security: 'security',
      Industry: 'industry',
      Research: 'research',
      Hardware: 'hardware',
      FlameWars: 'flame_wars',
      OsSoftware: 'os_software',
      CurcuitAnalysis: 'circuit_analysis',
      WebDevelopment: 'web_development',
      GameDevelopment: 'game_development',
      InternetNetworking: 'internet_networking',
      ArtificialIntelliegence: 'artificial_intelligence',
      LionProject: 'lion_project',
      BuySellTrade: 'buy_sell_trade',
      HelpfulBaubles: 'helpful_baubles',
      StudyChat: 'study_chat',
      GameknightChat: 'gameknight_chat',
      MovieknightChat: 'movieknight_chat',
    },
    Staff: {
      ModChat: 'mod_chat',
      UserOffenses: 'user_offenses',
    },
    Admin: {
      AdminChannel: 'admin_chat',
      BotLogs: 'bot_logs',
    },
    Private: {},
    Bot: {
      BotChannel: 'bot_commands',
      Verify: 'verify',
    },
  },
  Roles: {
    Unverifed: 'Un verified',
  },
};

export default Constants;
