name: Build and Linter Test

on:
  pull_request:
    branches:
      - master
    paths:
      - src/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: npm build
        uses: actions/npm@master
        with:
          args: build
      - name: npm lint
        uses: actions/npm@master
        with:
          args: run lint